### PR TITLE
Logo

### LINKED ISSUE #71: 1.1 Create and place logo on BP/Startpage
Description:
Design logo for cinema Ytterhogdal and present it in header/navbar top left corner on site

Dependencies: index.html #82, Navbar #1 

Placement/design:
In header/navbar top left corner (see design)
https://www.figma.com/file/hsTTbCAlERYrWQ2CpvgMBo/Untitled?node-id=0%3A1

Acceptance criteria:
Product owner must aprove logo, and logo must show in top left corner of header/navbar on site.

### PR DESCRIPTION
**Pull request by mhema42**
Hi, I´ve added the logo to the header in index.hml and made styling in _logo.scss
resolve #71

### CODE REVIEW

**Review by Nw84 — COMMENTED** [review]
It looks good, but shouldn't it be a text in/under the logo that says "Ytterhogdals bio". Or will we add that later ?

**Review by matodorovic — APPROVED** [review]
Looks nice. Just missing the title "Ytterhogdal Bio".

**Review by matodorovic — APPROVED** [review]
Looks good!! 👍

**Review by Nw84 — APPROVED** [review]
Looks good

**Pull request merged**
