### PR TITLE
About us

### PR DESCRIPTION
**Pull request by mhema42**
Added aboutus.html with styling

### CODE REVIEW

**Review by Nw84 — COMMENTED** [review]
It looks good, but shouldn´t we have the header and footer from the boiler plate there as well ?

**Comment by mhema42** [comment]
> It looks good, but shouldn´t we have the header and footer from the boiler plate there as well ?

Of course my misstake, now aboutus.html got header and footer from boiler plate with correct styling.

**Review by Nw84 — APPROVED** [review]
Good job Mats! It looks really good, exactly like the design 🥇

**Review by emmaambr — APPROVED** [review]
Good job!

**Pull request merged**
